#include "aws-curl-templates/aws_ec2_ami_templates.inc"
#include "aws-curl-templates/aws_ec2_ebs_templates.inc"
#include "aws-curl-templates/aws_ec2_hosts_templates.inc"
#include "aws-curl-templates/aws_ec2_net_templates.inc"
#include "aws-curl-templates/aws_ec2_reserved_templates.inc"
#include "aws-curl-templates/aws_ec2_scheduled_templates.inc"
#include "aws-curl-templates/aws_ec2_spot_templates.inc"
#include "aws-curl-templates/aws_ec2_vm_templates.inc"
#include "aws-curl-templates/aws_ec2_vpc_templates.inc"
#include "aws-curl-templates/aws_ec2_templates.inc"

#include "aws-curl-templates/aws_s3_templates.inc"

#include "aws-curl-templates/aws_rds_templates.inc"
